server {
    listen 1337;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Unity WebGL MIME types
    types {
        application/wasm                      wasm;
        application/javascript                js;
        application/octet-stream              data;
        application/json                      symbols.json;
        text/html                             html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
