name: Build AVR ROS2 Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., latest, 0.1)'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ros2-dev/Dockerfile.avr
          platforms: linux/amd64
          push: true
          pull: true
          tags: |
            droneblocks/dexi-avr-ros2:${{ inputs.tag }}
            droneblocks/dexi-avr-ros2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
